import './globals.css'
import type { Metadata } from 'next'
import { Archivo_Black } from 'next/font/google'

const archivo = Archivo_Black({  weight: "400",
subsets: ["latin"] })

export const metadata: Metadata = {
  title: 'DAGI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={archivo.className}>{children}</body>
    </html>
  )
}
